# Generated by Django 3.2 on 2021-11-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameC', models.CharField(max_length=100)),
                ('domainName', models.CharField(max_length=150)),
                ('companyName', models.CharField(max_length=150)),
                ('emailC', models.EmailField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('number', models.IntegerField(null=True)),
                ('message', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
